version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Add labels to enable auto-merge workflow targeting
    labels:
      - "dependencies"
      - "auto-merge"
    # Limit concurrent PRs to avoid overwhelming CI
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
    # Consistent commit messages
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Add labels for GitHub Actions updates too
    labels:
      - "dependencies"
      - "github-actions"
      - "auto-merge"
    open-pull-requests-limit: 3
    groups:
      ci-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
    commit-message:
      prefix: "chore(ci)"