jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto-approve PR
        run: |
          gh pr review ${{ github.event.number }} --approve --body "Auto-approved by workflow"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for auto-merge label and enable auto-merge
        run: |
          if gh pr view ${{ github.event.number }} --json labels --jq '.labels[].name' | grep -q "auto-merge"; then
            echo "Auto-merge label found, enabling auto-merge"
            gh pr merge ${{ github.event.number }} --auto --squash --delete-branch
          else
            echo "No auto-merge label found, skipping"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Repeat this for the auto-approve-and-merge job as well:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto-approve
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge
        uses: peter-evans/merge-now@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          merge_labels: dependencies
          merge_remove_labels: ""
          merge_commit_message: "pull-request-title-and-description"