name: Deploy Quartz to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Quartz site
        run: npx quartz build

      - name: Upload site to GitHub Pages
        uses: actions/upload-pages-artifact@v2  # Updated to latest version
        with:
          path: public  # Ensure this matches your Quartz output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3  # Updated to latest version